server:
  port: 8009
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource   # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.jdbc.Driver     # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/lqm?useUnicode=true&characterEncoding=utf8          # 数据库连接地址
    username: root                                  # 数据库用户名
    password: 11111111                            # 数据库连接密码
    hikari:
      pool-name: dataSourcePool
      maximum-pool-size: 2
# =====================================
#   REDIS CONFIG
# =====================================
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    caches:
  mapper-locations: classpath:com/mybatis/springbootmybatis/dao/*.xml
logging:
  level:
    com.mybatis.springbootmybatis.dao : debug




